name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
    
      - name: Assume AWS Role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1  # Set your desired AWS region
          role-to-assume: arn:aws:iam::600764632321:role/MyPipelineRole

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.assume-role.outputs.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.assume-role.outputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ steps.assume-role.outputs.session_token }}
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./
