name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
    
      - name: Assume AWS Role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          
          role-to-assume: arn:aws:iam::600764632321:role/MyPipelineRole
          aws-region: us-east-1  # Set your desired AWS region

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set your desired AWS region
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./
