name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: AKIAYXYC4ZUAXZ75LLTT
      AWS_SECRET_ACCESS_KEY: J36yvg3JQpawz2n2a+71anSwcS0ClOkm46iUJShK
      AWS_DEFAULT_REGION: us-east-1  # Set your desired AWS region

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./
